Makefile
basedosdados_api/settings/base.py
basedosdados_api/settings/prod.py

- Troca do caminho padrão do arquivo de log para `BASE_DIR / "django.log"` (permite a execução sem privilégios de superuser)
- Adiciona arquivo `Makefile` (comandos disponíveis descritos abaixo)
- Básico: [GNU Make](https://www.gnu.org/software/make/)
- Básico: [poetry](https://python-poetry.org/)
- Para executar com Docker: [Docker](https://www.docker.com/)
- Para executar com Docker: [Compose plugin](https://docs.docker.com/compose/install/linux/)
- Opcional, mas recomendado: [virtualenv](https://virtualenv.pypa.io/en/latest/), [miniconda](https://docs.conda.io/en/latest/miniconda.html) ou similares
**Observação**: caso deseje usar um ambiente virtual (recomendado), ele deve estar ativado antes da execução dos comandos.
- `make install`: instala dependências do repositório
- `make add …

feat: adiciona Makefile para auxiliar na manipulação do repositório

---

basedosdados_api/api/v1/models.py

Closes https://github.com/basedosdados/website/issues/414.

Lógica para `update`

---

basedosdados_api/api/v1/views.py

Relacionado a #113 e chat com @AldemirLucas 
- Não informar uma query agora no parametro `q` implica em retornar uma lista de todos os datasets (filtros são aplicáveis)
- Adiciona um parâmetro `filter_method`, que tem valor padrão `and` e tem valores possíveis `['and', 'or']`, para dizer se o filtro deve ser inclusivo ou exclusivo.
- `and` não é suportado para múltiplas `organization`. Caso seja solicitado, retornará um _Bad Request_
- `and` não é suportado para múltiplas `update_frequency`. Caso seja solicitado, retornará um _Bad Request_
- Adiciona os seguintes campos na serialização do dataset:
- Slug da `organization`
- Lista de temas no formato `{"name": "nome do tema", "slug": "slug_do_tema"}`
- Lista de tags no formato `{"name": "nome da tag", "slug": "slug_da_tag"}`
- ID da …

Ajustes no search

---

basedosdados_api/settings/dev.py

Quando roda-se o django dentro do compose (docker compose up), ao tentar logar no ADMIN, toma-se erro 403, csrf falhou.
Acredito ser por conta do NGINX que fica na frente do django.
Para permitir que rodemos tudo dentro do docker compose, adicionei essa config em dev. 
8080 refere-se a porta do serviço "api"
Dev, imagino eu, não deve rodar em prod, portanto não representa risco.

Quando em dev, cria exceção de CSRF, para podermos rodar dentro do docker.

---

basedosdados_api/settings/prod.py

A indexação das imagens é fundamental para melhoria do tempo da busca. Porém, o GCS exige que a chave expire em, no máximo, 7 dias. Assim, temos as seguintes soluções:
- rodar a reindexação toda semana
- colocar o bucket público
- se possível, colocar apenas as imagens de organização públicas.
@lucascr91 @JoaoCarabetta @rdahis @gabriel-milan @guialvesp1

expires GCS key in 7 days

---

basedosdados_api/api/v1/models.py
basedosdados_api/api/v1/tests/test_models.py
basedosdados_api/api/v1/tests/test_table_coverage.py

Correct bug in table coverages validation
Overlapping datetime_ranges must be validated by `Table`, instead of by `Coverage` and a `DateTimeRange` is not mandatory in `Coverage`. In situations where all table coverages had no datetime_ranges it raised an error that should not happen.
Created a new test file with this case. One of the previous tests was moved to this file, as it correlates
Rearrange all tests to be grouped by similarity

hotfix: do not raise error when all coverages have no datetime_ranges

---

basedosdados_api/account/signals.py

- Avoid sending emails on fixture loading
- Ignore account post save signal in fixture loading

fix: ignore account post save signal in fixture loading

---

.github/workflows/cd-dev.yaml

- Avoid this [release bug](https://github.com/basedosdados/backend/actions/runs/6179055937/job/16773334493)
- Use bash script to read pr branch name

fix: read dev branch name with script

---

basedosdados_api/api/v1/search_indexes.py
basedosdados_api/api/v1/views.py

- Hide `under_review` tagged tables
- Set first table id as published if available

fix: set first table id as published if available

---

.github/workflows/cd-staging.yaml

- Avoid staging deploy bug
- Set default cd staging branch to main

fix: set deploy staging branch to main

---

basedosdados_api/account/templates/account/activation_email_v1.html
basedosdados_api/account/templates/account/password_reset_email_v1.html

- Send beautiful emails
- Add email templates

feat: add email templates by lessa

---

basedosdados_api/api/v1/tasks.py
basedosdados_api/settings/base.py

fix: update import of tasks utils

---

basedosdados_api/api/v1/tasks.py
basedosdados_api/utils.py

- Limit tasks environments
- Add python decorator for huey tasks

feat: add decorator to run functions only in prod

---

bd_api/apps/payment/webhooks.py

- Bug
- Avoid using variable before is properly loaded

fix: set default google group env var inside function

---

bd_api/apps/core/views/dataset_redirect.py

- Bug
- Avoid access none objects in dataset redirect

fix: avoid access none objects in dataset redirect

---

bd_api/apps/payment/webhooks.py

- Bug
- Set `group_key` parameter of google groups functions as optional

fix: set group_key as optional parameter

---

bd_api/apps/payment/graphql.py

- Bug, fetching wrong model
- Get stripe subscription from internal subscription
- In unsubscribe endpoint

fix: get stripe subscription from internal subscription

---

bd_api/custom/graphql_jwt.py

- Enable file upload
- Avoid calling body after multipart request
- In this case, the body is read as a byte stream **just once**

fix: avoid calling body after multipart request

---

bd_api/apps/api/v1/tasks.py
bd_api/custom/client.py
bd_api/custom/model.py
bd_api/settings/base.py
poetry.lock
pyproject.toml

- Improve metadata
- Check if raw source urls return ok

feat: check if raw source urls return ok

---

bd_api/apps/api/v1/admin.py
bd_api/apps/api/v1/models.py

- Avoid invalid datetime ranges
- Limit datetime range fields in django admin

fix: limit datetime range fields in admin

---

bd_api/apps/api/v1/models.py

- Show coverages
- Update temporal coverages
```graphql
query all {
allDataset(first: 20) {
edges {
node {
name
coverage
}
}
}
allTable(first: 20) {
edges {
node {
name
coverage
fullCoverage
}
}
}
allColumn(first: 20) {
edges {
node {
name
coverage
}
}
}
}
```

fix: update temporal coverages

---

backend/apps/api/v1/search_views.py

Increase the results generated by the search function.
Currently in both production and staging environments, the metadata returned from a search has some limitations. This metadata includes themes, organizations, etc., and is capped at 10 results. As a result, users can only see a maximum of 10 themes in the sidebar. With these changes, users will be able to see more information to assist them in the search process.
https://github.com/basedosdados/backend/assets/5381250/aac736f8-3220-43f1-bd12-8c381a5111d5
Test in the staging environment and deploy to production as soon as possible.

chore: change facet quantity to 20 in dataset search

---

backend/apps/api/v1/graphql.py
backend/apps/api/v1/models.py

Improve the SQL queries generated in the backend.
This task simplifies the generated query to use a single, consolidated SQL table. By default, the generated SQL includes translations from the table, but it is now possible to pass a parameter that will always simplify the SQL.
The GraphQL query to be used: Pass includeTableTranslation as false to simplify the generated SQL query.
This PDF represents the two versions of the query generated from the same table.
[Query_diff.pdf](https://github.com/user-attachments/files/16076184/Query_diff.pdf)
Implement this in the frontend.

feat: add a new parameter to get_table_one_big_table_query

---

backend/apps/account/models.py
backend/apps/account/signals.py
backend/apps/account_payment/graphql.py
backend/apps/account_payment/webhooks.py

Nesse pr está inclusso algumas correções para o fluxo de pagamento com  o stripe. Abaixo a lista da correções e melhorias.
- Caso o usuário realize o pagamento via link (e não pela plaraforma) o email dela será adicionado ao grupo do google.
- Caso o usuário tenha sua subscription cancelada via stripe ou por falta de pagamento e ela nunca tenha acessado a plataforma seu email será removido do grupo do google.
- Caso o usuário tenha realizar o pagamento via link e depois tente realizar a criação de uma conta nova na plataforma da bd uma subscription será associada ao usuário automáticamente caso seja válida.
- Se pro algum motivo a subscription entrar em um estado não válido, como due date e afins a subscription na plataforma irá para o estado de desativada. Mesmo se o usuário não tiver …

fix: change stripe webhooks logic.

---

backend/apps/api/v1/models.py

Contexto: @tricktx e eu tentamos mexer no conjunto `id=e9493734-a30d-4f2b-9d88-8c8a6a217ce2` e recebemos um erro de 'internal server error'. Investigando no Grafana vi que parte do log é:
```
└ <Table: mundo_bm_learning_poverty.pais> File "/app/backend/apps/api/v1/models.py", line 1111, in clean units.append(datetime_range.unit.id)
└ <django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x7d43970eb510> 
└ <DateTimeRange: 2001(0)2001>
└ <method 'append' of 'list' objects>
└ [] AttributeError: 'NoneType' object has no attribute 'id' 
```
Isso é causado por a `coverage` da tabela não ter um `datetime_range.unit` associado, pois esse campo é opcional.

fix: if datetime_range has a unit

---

backend/apps/account_payment/graphql.py
backend/apps/account_payment/webhooks.py

Hotfix: fix: Handle missing unit_amount in StripePriceNode resolve_amount

fix: Handle missing unit_amount in StripePriceNode resolve_amount

---

.github/workflows/deploy-dev.yaml
.github/workflows/deploy-prod.yaml
.github/workflows/deploy-staging.yaml
.github/workflows/release-dev.yaml
.github/workflows/release-staging.yaml

Alterando as actions do GH para passar a utilizar a branch fixa referente ao seu próprio fluxo de deploy.

chore: update deployment workflows to use fixed branch references

---

backend/apps/api/v1/models.py

Consertando nossas contagens a nível de conjunto para esconder direto tabelas com `status=under_review` e dicionários.

fix: better counting without under_review and dictionaries

---

backend/apps/data_api/graphql.py
backend/apps/data_api/migrations/0001_initial.py

Após testes locais onde zerei o banco e refiz todas as migrações, esses parecem ser os reparos necessários para rodar as migrações em `development`.

fix: is_required, limit choices

---

backend/templates/admin/change_form.html

Renomeando botão que anteriormente se chamada "Ferramentas" para " Importar Colunas"

fix: mudar nome do botão Ferramentas para Importar Colunas

---

backend/apps/api/v1/urls.py
backend/apps/api/v1/views.py
backend/apps/core/static/core/css/main.css
backend/apps/core/static/core/js/ferramentas.js
backend/templates/admin/change_form.html

Este PR adiciona um novo botão "Importar Colunas" à interface administrativa do Django, localizado na categoria Tabelas. A funcionalidade permite que os administradores importem metadados de colunas diretamente de uma arquitetura previamente definida no Google Sheets, simplificando o processo de integração e manutenção de dados.
>![image](https://github.com/user-attachments/assets/e6346595-8191-40bc-ba4f-b6835bb2ecbb)
>Botão no admin
> ![image](https://github.com/user-attachments/assets/2c2f0de4-30c5-4dbb-8349-cde8b30e7f8a)
Depois de interação com o botão

feat: adding an “Importar Colunas” button

---

Dockerfile
docker-compose.override.yaml

This PR updates our `Dockerfile` to install and run the project using Poetry instead of pip. This avoids dependency resolution issues, as pip bypasses the `poetry.lock` file, potentially breaking the reproducibility that Poetr aims to provide.

fix: dockerfile
