basedosdados/backend

- basedosdados_api/api/v1/schema.py
- basedosdados_api/custom/graphql.py
> [FEATURE] Suporte total à geração automática de schemas para GraphQL

- basedosdados_api/custom/graphql.py
Sobrescreve o `_clean_fields` do `ModelForm` para tratar os casos:
- Usuário não precisar preencher todos os campos obrigatórios quando for atualizar um registro (quando fornecer o ID do registro)
- Usuário não precisar repetir os campos que não quer atualizar, somente preencher os que quer
**Limitações**: por algum motivo, os atributos base do `django-modeltranslation` (geralmente `name`) não parecem ser atualizados. Por outro lado, os derivados (`name_en` e `name_pt` são atualizados normalmente)
> [FIX] Conserta os updates para as mutations de `CreateUpdate`

- basedosdados_api/settings/prod.py
- poetry.lock
- pyproject.toml
> [FEATURE] django-storages config

- basedosdados_api/settings/prod.py
> removing key logfile from LOGGING in prod.py

- basedosdados_api/api/v1/views.py
temporarily replacing picture url from organizations, due to indexing issues
> chore: using image url from database instead of elasticsearch url

- basedosdados_api/api/v1/models.py
Achei um erro de nome de campo. Precisa de migração de banco pra resolver?
> fix: `raw_data_source.contains_structured_data`

- basedosdados_api/api/v1/models.py
> corrections in coverage inheritance

- scripts/migrations/20230803_migrate_users.py
- utils/graphql.py
> feat: migrate users

- basedosdados_api/api/v1/models.py
- basedosdados_api/api/v1/tests/test_models.py
- método `full_coverage` em `Table` com a lógica
- método `full_coverage` em `Dataset` retorna lista vazia
> adding logic to table full_coverage

- basedosdados_api/api/v1/models.py
- basedosdados_api/api/v1/tests/test_models.py
- when there's only one open or closed `coverage`, must return start date and end date for this `coverage`
> correcting logic to table full_coverage

- .github/workflows/cd-dev.yaml
- .github/workflows/cd-prod.yaml
- .github/workflows/cd-staging.yaml
- .github/workflows/ci.yaml
- .github/workflows/release-chart.yaml
- .github/workflows/release-dev.yaml
- .github/workflows/release-prod.yaml
- .github/workflows/release-staging.yaml
- Update the deploy flow
- To add more flexibility
- Current flow
- Merge dev/stag/prod triggers the respective release and deploy
- Proposed flow
- Dev: Open a pull request and add a label to deploy
- Stag: Merge a pull request to deploy
- Prod: Manual deploy, after QA
- I'm in favor of this flow because:
- Diminishes conflicts
- It enables fast deploys
> feat: update release and deploy flow

- .github/workflows/release-prod.yaml
- .github/workflows/release-staging.yaml
> fix: adapt release flow

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> fix: split issue templates

- .github/workflows/ci.yaml
- Lint pull request title
- Lint pull request title
- following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) convention
> feat: lint pull request title

- basedosdados_api/account/tests.py
- basedosdados_api/conftest.py
- Cover last changes
- Cover account confirmation
- Cover password reset endpoints
> test: cover email endpoints

- .gitignore
- basedosdados_api/settings/base.py
- docker-compose.yaml
- scripts/clean.py
- start-server.sh
- Ease loading fixtures in development
- Avoid the content types ordering bug
- Let's clean the content types tables created by the migrations
- Then load the fixtures on start up
> feat: load fixtures on docker compose startup

- basedosdados_api/api/v1/admin.py
- Add update index action to dataset 
- To avoid using reindex if a change isn't a breaking change
> fix: add update index action to dataset admin

- basedosdados_api/account/admin.py
- Hide unused model
- Hide registration token model
> chore: hide registration token

- basedosdados_api/api/v1/views.py
- basedosdados_api/settings/base.py
- basedosdados_api/settings/dev.py
- basedosdados_api/settings/prod.py
> fix: update google credentials config

- docker-compose.yaml
- Avoid unneeded warnings
- Ignore elastic search dev warnings
> chore: ignore elasticsearch development warnings

- .github/workflows/cd-dev.yaml
- .github/workflows/cd-staging.yaml
- .github/workflows/release-dev.yaml
- Limit staging releases to main branch
- Set dev branch name by artifact sharing
> fix: set dynamic development branch name

- basedosdados_api/account/signals.py
- basedosdados_api/account/tests.py
- basedosdados_api/core/management/commands/loadfixture.py
- basedosdados_api/utils.py
- Avoid sending unintended emails
- Isolate environment checks
- Add send activation email checks
> fix: add send activation email checks

- .github/workflows/release-dev.yaml
- Add flexibility to development environment deploy
- Select branch for development deploy before checkout
> feat: enable workflow dispatch trigger in dev environment

- basedosdados_api/api/v1/admin.py
- Improve metadata coverage
- Update number of columns in table metadata action
> fix: add number of columns to table metadata action

- basedosdados_api/core/management/commands/dumpfixture.py
- basedosdados_api/core/management/commands/loadfixture.py
- poetry.lock
- pyproject.toml
- scripts/sync.sh
- Ease refreshing staging data
- Add sync data between environments script
- The ideia is to limit account migration to only staff members
> feat: add sync data between environments script

- basedosdados_api/account/admin.py
- basedosdados_api/account/forms.py
- Increase visibility in account page
- Avoid sending email in manual account creation
- Increase visibility in account page
- Add profile filter
- Add career tab to account editor
- Avoid sending email in manual account creation
- Add is_active field to account creation form
> feat: add account extras

- basedosdados_api/account/admin.py
- Bug that prevents account edition
- Add career id to career inline
> fix: add id to career inline

- basedosdados_api/core/management/commands/dumpfixture.py
- This bug was going to turn all visitors into collaboratores in dev/stag environments
- Maintain the same profile in fixtures
> fix: maintain the same profile in fixtures

- scripts/dump.sh
- scripts/sync.sh
- Ease development
- Adapt sync script to dump
> feat: add dump script from sync

- basedosdados_api/api/v1/admin.py
- Avoid wrong metadata
- Don't update compressed file size
> fix: turn compressed file size into null

- basedosdados_api/custom/graphql.py
- Ease querying
- Add extra filters to graphql queries
> feat: add extra filters to graphql queries

- .github/workflows/cd-staging.yaml
- basedosdados_api/core/views/dataset_redirect.py
- Propagate update
- Update staging frontend url
> chore: update staging frontend url

- basedosdados_api/utils.py
- Enable deploy
- Avoid circular import in api utils
> fix: avoid circular import in api utils

- basedosdados_api/account/views.py
- basedosdados_api/api/v1/admin.py
- basedosdados_api/api/v1/signals.py
- basedosdados_api/logger.py
- basedosdados_api/middlewares.py
- basedosdados_api/settings/base.py
- basedosdados_api/settings/dev.py
- basedosdados_api/settings/prod.py
- poetry.lock
- pyproject.toml
- Increase information in logs
- Easing debugging of django admin
- Setup loguru library as the logger
- Use serialized logs with stacktraces
> feat: setup serialized logging with loguru

- basedosdados_api/logger.py
- basedosdados_api/middlewares.py
- To enable previous behaviour
- Set log level to debug
> fix: set log level to debug

- basedosdados_api/core/templates/500.html
- Avoid mixing types of errors in reports
- Update error 500 page message
> chore: update error 500 message

- basedosdados_api/api/v1/admin.py
- Avoid bug
- Replace search fields of observation level admin
> fix: replace search fields of observation level admin

- basedosdados_api/api/v1/admin.py
- basedosdados_api/api/v1/templates/admin/reorder_tables.html
- Override table/column ordering errors
- Add reset table/column order action
> fix: add reset table/column order action

- basedosdados_api/api/v1/admin.py
> fix: update action short description

- basedosdados_api/logger.py
- basedosdados_api/settings/dev.py
- basedosdados_api/settings/prod.py
- Decrease quantity of logs
- Set default log level as info
> feat: set default log level as info

- basedosdados_api/api/v1/models.py
- Undo bug
- Parse null coverage fields
> fix: parse null coverage fields

- .gitignore
- basedosdados_api/api/v1/tasks.py
- basedosdados_api/settings/base.py
- poetry.lock
- pyproject.toml
- start-server.sh
- Enable queueing tasks
- So that I can run some periodic updates
- Ad task queue huey with sqlite backend
> feat: add task queue huey

- basedosdados_api/logger.py
- Ease debug
- Avoid serializing debug logs
- Because it's really hard to read them
> fix: avoid serializing debug logs

- basedosdados_api/settings/base.py
- poetry.lock
- pyproject.toml
- Enable task queue
- Config huey to use redis
> feat: config huey to use redis

- basedosdados_api/api/v1/admin.py
- basedosdados_api/api/v1/models.py
- basedosdados_api/api/v1/signals.py
- basedosdados_api/api/v1/tasks.py
- basedosdados_api/settings/base.py
- docker-compose.yaml
- poetry.lock
- pyproject.toml
- Update table metadata periodically
- Add update table metadata on sundays
> feat: add update table metadata job

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- scripts/lint.py
- Standartize CI workflows
- Split CI workflow into two jobs
> chore: split github action ci jobs

- basedosdados_api/account/admin.py
- basedosdados_api/account/signals.py
- basedosdados_api/account/tests.py
- Enable mailing for testing
- Avoid restrictions that prevent mailing
> feat: enable mailing for testing

- scripts/migrations/20231006_migrate_storage.py
- Migrate website images/documents
- Add script to migrate website blobs
> feat: migrate website storage blobs

- .github/workflows/cd-dev.yaml
> build: add `REDIS_DB` env

- .github/workflows/release-staging.yaml
- Enable deploy without features
- Add manual deploy option to staging
> feat: add workflow dispatch option to staging cd

- .github/workflows/cd-dev.yaml
- .github/workflows/cd-prod.yaml
- .github/workflows/cd-staging.yaml
> fix: turn redis db env var into string

- basedosdados_api/settings/base.py
- Fix typo
- Rename redis host env var
> fix: rename redis host env var

- basedosdados_api/account/templates/account/password_reset_email_v1.html
- basedosdados_api/api/v1/admin.py
- basedosdados_api/settings/dev.py
> fix: adapt get_credentials for filepaths

- basedosdados_api/settings/base.py
- basedosdados_api/settings/prod.py
- Fix env var bug
- Add staticfiles default storage
> fix: add staticfiles key to storages

- .github/workflows/sync.yaml
- Ease collaboration
- Add action to sync databases between environments
> feat: add sync data action

- .github/workflows/sync.yaml
- Ease collaboration
- Add install kubectl step of data sync
> fix: adapt install kubectl step

- .github/workflows/sync.yaml
> fix: undo install kubectl step typo

- .github/workflows/sync.yaml
> fix: install kubectl using curl and install

- .github/workflows/sync.yaml
> fix: install gke gcloud auth plugin

- basedosdados_api/api/v1/urls.py
- basedosdados_api/core/management/commands/dumpfixture.py
- basedosdados_api/custom/graphql.py
- basedosdados_api/payments/admin.py
- basedosdados_api/payments/apps.py
- basedosdados_api/payments/models.py
- basedosdados_api/payments/tests.py
- basedosdados_api/payments/urls.py
- basedosdados_api/payments/views.py
- basedosdados_api/settings/base.py
- basedosdados_api/settings/dev.py
- basedosdados_api/settings/prod.py
- basedosdados_api/urls.py
- poetry.lock
- pyproject.toml
- Start stripe integration
- Add stripe libraries and app
> feat: add stripe integration skeleton

- basedosdados_api/account/models.py
> chore: remove deprecated functions

- basedosdados_api/payments/apps.py
- basedosdados_api/settings/base.py
> chore: override django stripe verbose name

- basedosdados_api/api/v1/tasks.py
- basedosdados_api/settings/base.py
- docker-compose.yaml
- start-server.sh
- Enable huey tasks logging
- Add logging setup before loading tasks
> fix: enable huey tasks logging

- .env.example
- basedosdados_api/api/v1/admin.py
- Enable update metadata action
- Isolate api fetches and errors
- Update source bucket name
- Update sample .env
> fix: update table metadata

- basedosdados_api/api/v1/tasks.py
- Avoid unneeded log
- Avoid logging in health check function
> chore: avoid logging the healthcheck

- scripts/migrations/20231006_migrate_storage.py
- Migrate storage
-Migrate category icons
- Add stop characters to regexp
> fix: adapt migrate storage script

- bd_api/apps/schemas/urls.py
- bd_api/apps/schemas/views.py
- Review modules
- Remove get endpoint without source data
> fix: remove missing schema view

- bd_api/apps/api/v1/admin.py
- bd_api/apps/api/v1/forms/__init__.py
- bd_api/apps/api/v1/forms/admin_form.py
- bd_api/apps/api/v1/models.py
- bd_api/apps/api/v1/templates/admin/table_change_form.html
- Improve admin
- Nitpick model class name
- Add cloud tables and updates to table admin
> feat: add cloud tables and updates to table admin

- bd_api/apps/api/v1/admin.py
- Issue
- Add observation level inline to information request admin
> feat: add observation level inline to information request admin

- bd_api/apps/api/v1/admin.py
- bd_api/apps/api/v1/forms/admin_form.py
- bd_api/apps/api/v1/models.py
- Improve admin
- Add coverage inline to admins
> feat: add coverage inline to admins

- bd_api/settings/base.py
- Increase devexp
- Add django extensions
- Previously was only in dev env
> feat: add django extensions to apps

- bd_api/apps/api/v1/apps.py
- Improve usability
- Update django admin app order
> fix: update django admin app order

- bd_api/apps/api/v1/admin.py
- Normalize interface
- Add autocomplete to updates inline
> fix: update updates auto complete

- bd_api/apps/core/urls.py
- bd_api/apps/core/views/__init__.py
- bd_api/urls.py
- Organize
- Move utils views to core app
> feat: move utils views to core app

- bd_api/apps/core/management/commands/loadfixture.py
- Bug
- Remove cascade from load fixture command
- To enable use of this script for loading test data
> fix: remove cascade from load fixture command

- bd_api/custom/graphql.py
- bd_api/custom/graphql_jwt.py
- Unblock user area functionality
- Improve account crud authentication
> feat: add ownership decorator

- bd_api/apps/payment/urls.py
- bd_api/apps/payment/views.py
- Unblock user area
- Add prices endpoint
> feat: add stripe prices endpoint

- .github/workflows/cd-dev.yaml
- .github/workflows/cd-prod.yaml
- .github/workflows/cd-staging.yaml
- Bug
- Just forgot to add the envvar to helm
> fix: add stripe live mode to helm

- .github/workflows/cd-dev.yaml
- .github/workflows/cd-prod.yaml
- .github/workflows/cd-staging.yaml
- Bug
- Set stripe live mode in helm
> fix: set stripe live code in helm

- bd_api/apps/payment/views.py
- Bug
- Applying method decorator in dispatch instead of post/put
> fix: apply method decorator in payments views

- bd_api/custom/logger.py
- bd_api/settings/local.py
- bd_api/settings/remote.py
- Ease inspecting test errors
- Ignore loggers from third party libraries
- I'm looking at you faker
> feat: ignore loggers from third party libraries

- bd_api/apps/api/v1/management/commands/reorder_columns.py
- bd_api/apps/api/v1/management/commands/reorder_tables.py
- scripts/migrations/20230224_migrate_ckan/ckan_django_main.py
> chore: remove aged todo comments

- bd_api/apps/payment/graphql.py
- Bug
- Add account to subscription in create subscription customer
> fix: add account to subscription in create

- bd_api/apps/api/v1/admin.py
- bd_api/apps/api/v1/models.py
- Improve table metadata
- Use cloud tables data to retrieve metadata
> fix: update metadata with cloud tables reference

- .github/workflows/release-prod.yaml
> feat: enable deploying from another branches

- bd_api/custom/graphql_auto.py
> fix: undo remove id resolver

- bd_api/apps/core/views/dataset_redirect.py
> chore: set default localhost port to 808

- bd_api/apps/api/v1/admin.py
- Bug
- Access coverage fields only if object exists
> fix: access coverage fields only if object exists

- bd_api/apps/api/v1/admin.py
- Enable table metadata update
- Enable update table metadata action again
> fix: add storage insights viewer role to service key

- bd_api/apps/api/v1/tasks.py
- Rebuild index weekly
- Add rebuild search index at sundays task
> feat: add rebuild index task

- bd_api/apps/payment/graphql.py
- Ease querying/mutating by id
- Add primary key field without graphql wrapper
> feat: add _id field to stripe price

- bd_api/apps/api/v1/tasks.py
- Update search index daily
- Add update search index task
> feat: add update search index task

- bd_api/apps/api/v1/signals.py
- Propagate metadata updates to search
- Update dataset index after date time range update
> fix: add date time range case to update index hook

- bd_api/settings/base.py
- Convenience
- Add common links
> chore: add more topmenu links

- bd_api/apps/api/v1/tasks.py
- Avoid too much logs
- Our log processing system is frail
- Decrease huey health check frequency
> chore: decrease huey health check frequency

- bd_api/settings/base.py
- Nitpick
- Add prefect top menu link
> chore: add prefect top menu link

- bd_api/apps/account/admin.py
- bd_api/apps/account/models.py
- Enable internal subscription management
- Add subscription model to django admin
> feat: add subscription to django admin

- bd_api/apps/account/models.py
- bd_api/apps/payment/graphql.py
- Improve stripe integration
- Return subscription info in account
- Though it won't work right now
- Create stripe customer only if doesn't exist
- Turn customer create parameters into optional
> feat: improve stripe integration constraints

- bd_api/apps/api/v1/tasks.py
- Avoid too many logs
- Though they are so many
- Delete health check ping
> chore: kill huey health check

- .env.docker
- docker-compose.yaml
- Ease docker setup
- Split environment variables and create a docker env file
> chore: split environment variables files

- bd_api/apps/account/admin.py
- bd_api/apps/account/models.py
- bd_api/apps/account/tasks.py
- bd_api/apps/payment/webhooks.py
- Load current subscribers
- Support email update in stripe
- Add action/task to load current subscribers
- Add webhook handler to update email if changed
> feat: add sync subscription action and task

- bd_api/apps/account/tasks.py
> fix: skip mailing on sync subscription task

- bd_api/apps/api/v1/signals.py
- It's working
- But we run on low power
- Disable indexing after update
> fix: disable indexing after update

- bd_api/custom/graphql_auto.py
> fix: avoid accessing subscriber field on account

- bd_api/apps/api/v1/signals.py
- Bug
- Undo hotfix of disabling bd signal processor
> fix: enable bd signal processor

- bd_api/apps/account/tasks.py
- Searching for bugs in development env
- Temporarily disable task decorator in sync subscription
> fix: turn sync subscription into function

- bd_api/apps/account/tasks.py
- bd_api/apps/payment/webhooks.py
- Log
- Log sync subscription success
> feat: add info log to sync subscription

- bd_api/custom/graphql_auto.py
- Bug
- Allow methods and properties as graphql fields
- To undo this regression
> fix: allow methods and properties as graphql fields

- bd_api/custom/graphql_auto.py
- Bug
- Initialize id filter field
> fix: initialize id field filter

- bd_api/apps/account/models.py
- bd_api/custom/graphql_auto.py
- Normalize subscription fields
- From "BD Pro Completo", to "bd_pro"
- Add current subscription product metadata
> feat: add current subscription product metadata

- bd_api/custom/graphql_auto.py
> fix: set default filter fields

- bd_api/apps/account/tasks.py
- bd_api/apps/api/v1/tasks.py
- bd_api/settings/base.py
- start-server.sh
- Log
- Keep only essential logs
> feat: only log essential information

- bd_api/apps/account/tasks.py
- bd_api/apps/api/v1/tasks.py
- bd_api/utils.py
- Bug
- Adapt production only decorator
> fix: adapt production only decorator

- bd_api/apps/payment/webhooks.py
- Bug
- Avoid saving subscription if customer doesn't exist
> fix: avoid saving subscription if customer doesn't exist

- bd_api/apps/account/models.py
- Ease development
- Adapt bd pro properties of account
> feat: adapt subscription to bd pro properties

- bd_api/apps/api/v1/tasks.py
- Visibility
- Log update table metadata task
> feat: log update table metadata task

- bd_api/custom/graphql_auto.py
- Bug
- Filter not showing in graphql
- Increase graphql depth of filter generation
> fix: increase graphql depth of filter generation

- .github/workflows/cd-dev.yaml
- .github/workflows/cd-prod.yaml
- .github/workflows/cd-staging.yaml
- bd_api/apps/api/v1/admin.py
- bd_api/apps/api/v1/tasks.py
- bd_api/custom/client.py
- bd_api/settings/base.py
- Increase visibility of table metadata update
- Send discord message with table metadata update warnings
> feat: report table metadata execution

- bd_api/apps/api/v1/tasks.py
- Improve update metadata message
- Add links to update metadata message
> feat: add links to metadata update logs

- bd_api/apps/api/v1/search_engines.py
- bd_api/apps/api/v1/search_indexes.py
- bd_api/settings/base.py
> feat: split indexing function of search

- bd_api/apps/account/graphql.py
- bd_api/apps/schema.py
- Delete account picture
- Add delete account picture mutation
> feat: add delete account picture mutation

- bd_api/apps/account/models.py
- bd_api/custom/graphql_auto.py
- bd_api/custom/graphql_jwt.py
- bd_api/custom/model.py
- Avoid hardcoding/reproducibility
- Update graphql mutation decorator
> feat: update graphql mutation decorator

- bd_api/apps/account/models.py
- bd_api/custom/graphql_auto.py
- bd_api/custom/graphql_jwt.py
- bd_api/custom/model.py
- Avoid creation of admins by API
- Add option to hide mutation fields
> feat: add option to hide mutation fields

- bd_api/apps/account/views.py
- Bug
- Replace hardcoded variables from password reset
> fix: replace hardcoded variables from password reset

- .github/workflows/cd-dev.yaml
- .github/workflows/cd-prod.yaml
- .github/workflows/cd-staging.yaml
- Ease deploy
- Add `workflow_dispatch` to cd actions
> feat: update github actions

- bd_api/apps/core/management/commands/dumpfixture.py
- bd_api/apps/core/management/commands/loadfixture.py
- Enable dumping
- Update fixture commands
> fix: update fixture commands

- bd_api/apps/api/v1/models.py
- bd_api/custom/graphql_auto.py
- Ease join visibility
- Add neighbors property with similar tables and columns
> feat: add table neighbors

- bd_api/apps/api/v1/models.py
- Improve visualization of related entities
- Add dataset and table ids to neighbors property
> feat: improve table and column neighbors

- .github/workflows/cd-dev.yaml
- .github/workflows/cd-prod.yaml
- .github/workflows/cd-staging.yaml
- bd_api/apps/api/v1/tasks.py
- bd_api/utils.py
- Execute some tasks at most once
- Add task worker env variables and utilities
> feat: add task worker deployment env variables

- .github/workflows/ci.yaml
- poetry.lock
- pyproject.toml
- Improve toolset
- Add pytest coverage ci step
> chore: add pytest coverage ci step

- bd_api/apps/api/v1/models.py
- Metadata
- Add table and raw data source last updated at
> feat: add table and raw data source last updated at

- bd_api/apps/api/v1/tasks.py
- fix: format update table metadata message
- fix: format update table metadata message
> fix: update table metadata message

- bd_api/apps/api/v1/models.py
- bd_api/custom/logger.py
- Decrease the number of suggestions
- Rank and filter table/column neighbors
> feat: rank and filter table/column neighbors

- bd_api/apps/account/models.py
- bd_api/apps/api/v1/models.py
- bd_api/custom/graphql_auto.py
- bd_api/custom/model.py
- Avoid boilerplate
- Turn python properties into graphql attributes
> feat: turn python properties into graphql attributes

- bd_api/apps/api/v1/tasks.py
- Avoid flaky tasks
- Add [retry options](https://huey.readthedocs.io/en/latest/guide.html#retrying-tasks-that-fail) to huey tasks
> fix: retry index tasks

- bd_api/apps/account_auth/views.py
- Finish grafana login
- Update authentication and redirect flow
> fix: update authentication and redirect flow

- bd_api/apps/account_payment/graphql.py
- bd_api/apps/api/v1/graphql.py
- bd_api/apps/schema.py
- Organization
- Organize account and payment graphql classes
> chore: organize account and payment graphql classes

- bd_api/custom/graphql_auto.py
- bd_api/custom/graphql_jwt.py
- bd_api/custom/model.py
- Improve fine-grained authentication
- Add custom authentication decorator by model
> feat: prepare for graphql query authentication

- bd_api/apps/account/signals.py
- Reactivate customers
- Add a function to send welcome email to previous subscribers
> feat: add function to send welcome email to previous subscribers

- bd_api/apps/account/models.py
- bd_api/apps/account_payment/graphql.py
- Subscription
- Add subscribers info in subscription
- Check if account has active subscription before creation
> feat: add subscription check and info

- .github/workflows/deploy-prod.yaml
- charts/basedosdados-api/templates/deployment.yaml
- Optimization of resources
- Decrease replicas without downtime
> chore: decrease replicas without downtime

- backend/apps/api/v1/admin.py
- Bug
- Access field only if exists
> fix: access field only if exists

- backend/apps/account_payment/graphql.py
Fix a major issue on the website.
Add more information about the Stripe prices into the GraphQL to be used on the website.
Implement the changes in the frontend.
> feat: return more info from StripePriceNode

- backend/apps/account_payment/graphql.py
Add the 7 trial days to all plans. Avoid to apply the trial when the user already has a subscription in the past.
Test in staging and in dev enviroment before push to production.
> fix: add trial period for new subscriptions

- backend/apps/core/management/commands/fetch_metabase.py
Log user used in the error message.
> feat: handle non-200 response in fetch_metabase.py

- backend/apps/core/management/commands/fetch_metabase.py
- backend/apps/core/management/commands/populate.py
- Using pagination techniques to download all data from Metabase.
- Recreating all many-to-many connections between models.
> fix: fetch Metabase data in pagination to improve performance

- backend/custom/graphql_jwt.py
feat: Import Account model in CustomVerify mutation
> feat: Import Account model in CustomVerify mutation

- backend/apps/core/management/commands/populate.py
> fix: Use item.get() method to retrieve field values in populate.py

- .github/workflows/deploy-prod.yaml
Corrigir problema de super dimensionamento de memória que estava inpedindo o pod de prod da api de subir.
> chore: Update CPU and memory limits for deployment in deploy-prod.yaml

- backend/apps/account/models.py
- backend/custom/graphql_jwt.py
Adicionando novos campos do Stripe no modelo Subscription para ser retornado no Graphql bem como no VerifyToken query.
> feat: add more fields related to Stripe

- backend/apps/account_payment/webhooks.py
Alterando método de como é verificado se o usuário já possui subscriptions durante o fluxo de criação de sub em modo trial.
> fix: Update webhook for create subscription

- backend/apps/account_payment/graphql.py
- backend/apps/account_payment/webhooks.py
- backend/custom/logger.py
Adicionando suporte ao cupom na api do backend. Não somente isso mas também foi adicionado uma nova mutation para validação de cupom. Nesse caso também retornará o valor de desconto a ser aplicado.
> fix: add promotion code support to subscription creation

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-staging.yaml
- .github/workflows/release-dev.yaml
- .github/workflows/release-prod.yaml
- .github/workflows/release-staging.yaml
Melhoria no fluxo de deploys no Github actions.
> feat: add branch filtering to deployment workflows

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-staging.yaml
- .github/workflows/release-dev.yaml
- .github/workflows/release-prod.yaml
- .github/workflows/release-staging.yaml
> Merge Dev com Staging

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-staging.yaml
- .github/workflows/release-dev.yaml
- .github/workflows/release-prod.yaml
- .github/workflows/release-staging.yaml
> Merge Staging em Production

- backend/apps/account_payment/graphql.py
- backend/apps/account_payment/webhooks.py
Corrigindo o cancelamento da sub via Stripe.
> fix: cancel subscription with Stripe

- .github/workflows/deploy-staging.yaml
- backend/apps/account_payment/graphql.py
- backend/apps/account_payment/webhooks.py
> Merging dev em Staging

- backend/apps/api/v1/schemas.py
- backend/apps/api/v1/search_indexes.py
- backend/apps/api/v1/search_views.py
Mudanças necessárias para as chamadas do FE com tradução.
> feat: adapt search to accept locales and return translated fields

- backend/apps/account/views.py
Reset and Activations emails are not being sent
Debbug in the functions that dispatch the email
Production Bug
[Related Issue](https://github.com/orgs/basedosdados/projects/14/views/1?filterQuery=assignee%3Aisabelmeister&pane=issue&itemId=104046410&issue=basedosdados%7Cbackend%7C790)
> fix: reset and activate emails

- backend/apps/api/v1/urls.py
- backend/apps/api/v1/views.py
- backend/apps/core/static/core/css/main.css
- backend/apps/core/static/core/js/ferramentas.js
- backend/templates/admin/change_form.html
Adicionando POC para botão upload_columns em Tables.
> feat: Adicionando POC para botão upload_columns em Tables 

- backend/apps/account/migrations/0001_initial.py
- backend/apps/account/migrations/0021_rename_role_career_role_old_and_more.py
- backend/apps/account/migrations/0022_rename_role_new_career_role_and_more.py
- backend/apps/account/migrations/0023_alter_career_role_old_alter_career_team_old.py
- backend/apps/account/models.py
- backend/apps/api/v1/management/commands/reorder_tables.py
- backend/apps/api/v1/migrations/0003_alter_column_is_closed_alter_dataset_is_closed_and_more.py
- backend/apps/core/management/commands/fetch_metabase.py
Este PR resolve um problema onde arquivos existentes no branch `staging` estavam sendo incorretamente marcados como alterações novas quando comparados com branchs vindo de `main` durante a criação de pull requests.
Anteriormente, ao criar um PR de uma branch originalmente criada de `main` para o `staging`:
- Arquivos idênticos entre os dois branches apareciam como alterações
- Isso causava confusão visual na revisão de código
- Comprometia a eficiência do processo de revisão
> ci: sync staging branch with main

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-staging.yaml
- charts/basedosdados-api/templates/deployment.yaml
Removed chatbot related env variables from the deployment workflow files, so we don't have to change them. They will be added as secrets.
> fix: chatbot deploy

- .github/workflows/deploy-dev.yaml
Este Pull Request tem como objetivo atualizar a branch atual com as últimas alterações da branch main, garantindo que a base de código esteja alinhada com as mudanças mais recentes.
> ci: sync staging and main (#833, #835, #836)

- backend/apps/chatbot/utils/stream.py
Fixes the parsing logic for parallel tool calls during response streaming.
> fix: correctly parse parallel tool calls

- .github/workflows/deploy-dev.yaml
Este Pull Request tem como objetivo atualizar a branch atual com as últimas alterações da branch main, garantindo que a base de código esteja alinhada com as mudanças mais recentes.
> chore: sync dev and main (#844, #851) 

- poetry.lock
The `chatbot` package has been updated to `v0.6.1`, which adjusts the SQL Agent system prompt so that responses are generated in the same language as the user’s original question.
> chore: update chatbot package to `v0.6.1`

- backend/apps/chatbot/agent/tools.py
- backend/apps/chatbot/views.py
Esse PR adiciona uma limitação no consumo de dados do BigQuery para consultas em todas as tabelas, incluindo BD Pro.
> feat: query billing limit

- backend/apps/chatbot/agent/react_agent.py
- backend/apps/chatbot/utils/stream.py
- Handles empty AI messages (i.e., no content and no tool calls)
- Fix JSON object truncation
> fix: empty ai message

- backend/apps/chatbot/agent/tools.py
- backend/apps/chatbot/utils/stream.py
- Add usage guides to the LLM context: The usage guides are being downloaded from the [website](https://github.com/basedosdados/website/tree/main/next/content/userGuide/pt) repository and added to the output of the `get_dataset_details` tool.
- Improved the processing of AI messages content during streaming.
> chore: add usage guides
